name: "Issue updated"
on:
  issues:
#     types: [opened, labeled]
    types: [edited]

jobs:
  issue-edited:
    name: issue edited
    runs-on: ubuntu-latest
    steps:
      - name : Check
        shell: bash
        run : echo "Issue title ${{ github.event.issue.changes }}"
